# 課題（iLect上で解答を提出してください）

## Numpy、Scipy、Pandas、Matplotlibの基礎

 $n\times n$ 正方行列をインプットデータとして、その行列式を返り値とする関数を作成してください。

例えば、行列 $\begin{bmatrix}3 & 2 & 1 \\
      5 & 3 & 7 \\
      1 & 1 & 1\end{bmatrix}$
は、次のようにnumpyの配列として扱います。

```python
A = np.array([[3,2,1],[5,3,7],[1,1,1]])
```


提出するときは、以下の点に注意してください。  
>- 以下の関数homeworkの!!WRITE ME!!に処理を書いてください。(**「!!WRITE ME!!」は消して、記入してください。**)
>- 実際の提出は記述されたhomework関数全てになり、**提出場所はilect上にあるHomeworkからSaveしてください。Solutionに関数を貼り付けます。**
>- 返り値は数値型です。

In [0]:
# common
import numpy as np
from numpy import linalg as LA

In [0]:
# working place. everything 
def homework(A):
    my_result = LA.det(A)
    return my_result

In [0]:
A = np.array([[3,2,1],[5,3,7],[1,1,1]])
B = np.array([[1,3],[2,4]])
print(A)
print(B)
print(homework(A))
print(homework(B))

[[3 2 1]
 [5 3 7]
 [1 1 1]]
[[1 3]
 [2 4]]
-6.0
-2.0


In [0]:
3*3*1+1*1*5+2*7*1-1*1*3-2*5*1-3*1*7

-6